- src/Visualization.jl
Plot recipes currently describe plot primitives that live in an `Axis` but can not change the `Axis` parameters. Therefore, with plot recipes, we can't currently include `Colorbar`s, add interactions, and in general, customize the `Axis`.
In this PL we address #5, and we change the plot function so now it can take a `GridPosition` and plot into it. This enabled us to add the following features:
- Added integration to plot the contraction paths into subplots.
- Added the possibility to create 3D plots.
```julia
julia> using Makie
julia> using GLMakie
julia> tn = rand(TensorNetwork, 60, 3)
TensorNetwork{Arbitrary}(#tensors=60, #inds=90)
julia> f = Figure(backgroundcolor="ivory", resolution=(1000, 700))
julia> scatter(f[1,1], 1..4, log)
Makie.AxisPlot(Axis (1 plots), …
```
> Refactor visualization functions

- src/Visualization.jl
We add `labels` as a keyword argument into both `plot` and `plot!` functions. This argument is `false` by default, but if it's `true`, the plot displays the index label of each edge.
```julia
julia> using CairoMakie
julia> using Makie
julia> tn = rand(TensorNetwork, 10, 3)
TensorNetwork{Arbitrary}(#tensors=10, #inds=15)
julia> plot(tn; labels=true)
(Scene (800px, 600px):
0 Plots
1 Child Scene:
└ Scene (800px, 600px), Axis (1 plots), Combined{GraphMakie.graphplot, Tuple{Graphs.SimpleGraphs.SimpleGraph{Int64}}})
julia> [tensor.labels for tensor in tn.tensors]
10-element Vector{Tuple{Symbol, Vararg{Symbol}}}:
(:m, :d, :j)
(:k, :i, :o)
(:c, :f, :d)
(:l, :c, :f)
(:a, :m, :n, :j, :g, :o)
(:h,)
(:k, :b, :i)
(:a, :e)
(:e, :l)
(:h, :g, :b, :n)
```
> Add `labels` keyword argument into plot functions

- src/Visualization.jl
Small fix from last PR, the plot function crashed since the function `labels` conflicts with the keyword argument `labels`.
> Fix from last PR: bug in plot functions

- src/Transformations.jl
- test/Transformations_test.jl
This PR addresses the bug found in the `transform` function. This bug was not found before because this function is not included in the tests at the moment.
Previously, we could not call the `transform` function since the `transformations` argument accepted the type `Sequence{Transformation}` and `Transformation` is an abstract type. This is now changed so it accepts a `Sequence` of `struct`s that inherit from `Transformation`.
```julia
julia> tn = TensorNetwork([Tensor(rand([2, 2, 2]...), tuple([:i, :j, :k]...)), Tensor(rand([2, 2, 2]...), tuple([:i, :k, :l]...)), Tensor(rand([2, 2, 2]...), tuple([:i, :l, :j]...))])
TensorNetwork{Arbitrary}(#tensors=3, #inds=4)
julia> tn = transform(tn, [Tenet.HyperindConverter()])
TensorNetwork{Arbitrary}(#tensors=4, #inds=6)
``` …
> Fix crash in `transform` function: `transformations` argument

- src/Visualization.jl
From issue #21 
In this PR we fix the `plot` functions: now these can plot `TensorNetworks` with hyperedges. The hyperedges are visualized with a grey diamond-shaped COPY tensor, with grey indices coming from it.
```julia
julia> using GLMakie
julia> using Makie
julia> tn = TensorNetwork([Tensor(rand([2, 2, 2]...), tuple([:i, :c, :k]...)), Tensor(rand([2, 2, 2, 2]...), tuple([:i, :k, :s, :p]...)), Tensor(rand([2, 2, 2]...), tuple([:i, :s, :c]...)), Tensor(rand([2, 2]...), tuple([:p, :t]...))])
TensorNetwork{Arbitrary}(#tensors=4, #inds=6)
julia> plot(tn; labels=true)
(Scene (800px, 600px):
0 Plots
1 Child Scene:
└ Scene (800px, 600px), Axis (1 plots), Combined{GraphMakie.graphplot, Tuple{Graphs.SimpleGraphs.SimpleGraph{Int64}}})
julia> [tensor.labels for tensor in …
```
> Fix plots for `TensorNetworks` with hyperedges

- src/Visualization.jl
In this PR we address issue #32: we fix the plot functions so now we can visualize the open indices that a `TensorNetwork` may have. This is done by adding 'ghost' tensors of size zero at the edge of each open index.
```julia
julia> using GLMakie; using Makie
julia> tn = TensorNetwork([Tensor(rand([2, 2, 2, 2, 2]...), tuple([:i, :t, :k, :x, :y]...)), Tensor(rand([2, 2, 2, 2]...), tuple([:i, :k, :s, :p]...)), Tensor(rand([2, 2]...), tuple([:i, :s]...)), Tensor(rand([2, 2, 2]...), tuple([:p, :t, :z]...))])
TensorNetwork{Arbitrary}(#tensors=4, #inds=8)
julia> using NetworkLayout
julia> plot(tn; labels=true, layout=Spring(dim=3))
Tuple{Symbol, Vararg{Symbol}}[(:p, :t, :z), (:i1, :t, :k, :x, :y), (:i2, :k, :s, :p), (:i3, :s), (:i1, :i2, :i3), (:y, :x), (:z,)]
julia> …
```
> Add support for visualization of open indices in plot functions

- src/MatrixProductState.jl
- test/MatrixProductState_test.jl
In `MatrixProductState`, we first have the labels sorted in `(:l, :r, :i, :o)` and then we want to have it in `order`, but the permutator permutes from `order` to `(:l, :r, :i, :o)`, so instead of `permute!` we need `invpermute!`. This didn't fail in tests because in the case we considered the permutation was the same as the inverse permutation.
This code failed without this PR, and now works properly.
```julia
julia> using Tenet; using Test
julia> @test begin
arrays = [rand(3, 1), rand(3, 1, 3), rand(1, 3)]
MatrixProductState{Open}(arrays, order = (:r, :p, :l)) isa TensorNetwork{MatrixProductState{Open}}
end
Test Passed
```
> Fix label permutation on `MatrixProductState`

- src/TensorNetwork.jl
- test/TensorNetwork_test.jl
This PR introduces a new `Base.replace!` function for the `TensorNetwork` type (issue #48). The function allows users to replace an existing `Tensor` within a `TensorNetwork`  with a new `Tensor`, provided that the new `Tensor` has `labels` that are a permutation of the old `Tensor`'s `labels`.
The implementation ensures that the `TensorNetwork`'s `inds` field is properly updated to maintain consistency within the network.
Example:
```julia
julia> using Tenet; using Test
julia> ψ = rand(MatrixProductState{Open}, 16, 2, 8) # Create a random tensor network
TensorNetwork{MatrixProductState{Open}}(#tensors=16, #inds=31)
julia> old_tensor = tensors(ψ, 2) # Retrieve a tensor from the network
2×4×2 Tensor{Float64, 3, Array{Float64, 3}}:
[:, :, 1] =
0.429373   0.473947  0.475461   0.0111029 …
```
> Add `Base.replace!` function for `Tensor`s in a `TensorNetwork`

- src/Quantum/MatrixProductOperator.jl
- src/Quantum/MatrixProductState.jl
- test/MatrixProductOperator_test.jl
- test/MatrixProductState_test.jl
This PR addresses the issue "Incorporate `labels` representation for physical indices of each `Tensor` within a `State`" (fix #49). The implementation enhances the `meta` field of a `Tensor` within a `State` or `Operator` by including a dictionary that links the physical representation of each index (left, right, ...) with its respective label. This feature has been implemented for all the currently supported structs, `MatrixProductState` and `MatrixProductOperator`.
Implemented changes:
1. Updated the code for `MatrixProductState{Open}`, `MatrixProductState{Closed}`, `MatrixProductOperator{Open}`, and `MatrixProductOperator{Closed}` to include the new `alias` dictionary within the `meta` field of a `Tensor`.
2. Added test cases to ensure that the `alias` dictionaries in the tensors are …
> Enhance `Tensor` metadata with label `alias` mapping

- src/Quantum/MatrixProductState.jl
- test/MatrixProductState_test.jl
This PR addresses the issue with the `rand` function for generating random `MatrixProductStates` (MPS) with an odd number of tensors. Previously, the function produced an error when the number of tensors in the argument was odd:
```julia
julia> ψ = rand(MatrixProductState{Open}, 7, 2, 32)
ERROR: DimensionMismatch: size(9edf0aa5-219f-4849-99d3-a85b569b6773)=16 but should be 8
```
Now, the `rand` function correctly handles cases where the number of tensors is odd. Also, we have added tests to ensure its correct behavior.
> Fix `rand` function for odd-length `MatrixProductState`

- src/TensorNetwork.jl
- test/TensorNetwork_test.jl
The `contract` function for `TensorNetworks` raised an error when trying to contract a tensor network defined with a list of `Tensor`s. In this PR we have fixed this small problem and added tests covering the previous error.
To illustrate the issue, we provide an example of the previous error:
```julia
julia> A = Tensor(rand(2, 2, 2), (:i, :j, :k))
2×2×2 Tensor{Float64, 3, Array{Float64, 3}}: ...
julia> B = Tensor(rand(2, 2, 2), (:j, :l, :m))
2×2×2 Tensor{Float64, 3, Array{Float64, 3}}: ...
julia> tn = TensorNetwork([A, B])
TensorNetwork{Arbitrary}(#tensors=2, #inds=5)
julia> contract(tn)
ERROR: MethodError: Cannot `convert` an object of type Index to an object of type Symbol
Closest candidates are:
convert(::Type{T}, ::T) where T at Base.jl:61
Symbol(::Any...) at …
```
> Fixed issue in `contract` function for `TensorNetwork`

- src/Transformations.jl
- test/Transformations_test.jl
This PR addresses the issue #14 (resolves #14) by introducing the `DiagonalReduction` transformation in the `transform!` function for `TensorNetwork`s. This transformation applies diagonal reduction (as defined [here](https://arxiv.org/pdf/2002.01935.pdf)) to simplify the tensor network while preserving its mathematical properties. The key idea is to minimize the number of indices by identifying tensors with a certain diagonal structure and collapsing these indices, potentially leading to computational efficiency.
In addition to the implementation of the transformation, this PR includes tests to ensure correctness and robustness of the new method.
```julia
julia> data = [1.0 0.0; 0.0 1.0;;; 1.0 0.0; 0.0 1.0] # We can clearly see that the first and second indices are …
```
> Add `DiagonalReduction` transformation for `TensorNetwork`

- src/Transformations.jl
- test/Transformations_test.jl
This PR addresses the issue #16 (resolves #16)  by introducing the `AntiDiagonalGauging` transformation in the `transform!` function for `TensorNetworks`. This transformation applies the anti-diagonal gauging (as defined [here](https://arxiv.org/pdf/2002.01935.pdf)) to modify the tensor network while preserving its mathematical properties.
The `AntiDiagonalGauging` transformation reverses the order of some indices for tensors that fulfill an anti-diagonal condition. While this transformation alone does not directly contribute to computational efficiency, it prepares the tensor network for further simplifications by creating tensors with diagonal indices. These tensors can then be simplified using the `DiagonalReduction` transformation, which was implemented in PR #58.
In addition to the …
> Add `AntiDiagonalGauging` transformation for `TensorNetwork`

- src/Transformations.jl
- test/Transformations_test.jl
This PR addresses a previously overlooked scenario in the `DiagonalReduction` transformation of the `transform` function. Specifically, it targets instances where the index to be reduced is included in `skip_inds`, which is set to be the open indices of the network by default. In such cases, the transformation previously failed to correctly reduce the dimension of a `Tensor` in a `TensorNetwork`.
To fix this,  we have introduced a COPY tensor whenever an index is reduced over a `Tensor` with an index in `skip_inds`. to illustrate this, let's consider a `TensorNetwork` $`TN=T^{1}_{ijk}T^{2}_{jkl} `$, and we want to reduce the diagonal indices $ij$ where $i$ is on `skip_inds` since it is an open index. A regular reduction would lead to $`\tilde{TN}=T^{1}_{ik} T^{2}_{ikl}`$, but as a result, …
> Fix `DiagonalReduction` tranformation for reduction over `skip_inds`

- src/Transformations.jl
- test/Transformations_test.jl
This PR addresses the issue #17 (resolves #17) by introducing the `ColumnReduction` transformation in the `transform!` function for `TensorNetwork`s. This transformation applies the column reduction (as defined [here](https://arxiv.org/pdf/2002.01935.pdf)) to simplify the tensor network. The key idea is to reduce the rank of the tensors that have a dimension where all but a "column" is filled with zeros.
Furthermore, we have extended the scope of this method to handle cases where more than one column contains non-zeros but specific columns are entirely zero-filled. This allows the reduction of the index dimensionality where columns are filled with zeros.
In addition to implementing the transformation, this PR includes tests to ensure the correctness and robustness of the new method.
The …
> Implement `ColumnReduction` transformation for `TensorNetwork`

- Project.toml
- ext/TenetQuacExt.jl
- src/Helpers.jl
- src/Quantum/MP.jl
- src/Quantum/Quantum.jl
- src/TensorNetwork.jl
- test/Helpers_test.jl
- test/MatrixProductOperator_test.jl
- test/MatrixProductState_test.jl
- test/Project.toml
- test/Quantum_test.jl
- test/integration/Quac_test.jl
This PR replaces the `metadata` dictionary proposed in #55 with a `NamedTuple` defined as a parameter of the `TensorNetwork` type.
```julia
struct TensorNetwork{A<:Ansatz} ... end
struct TensorNetwork{A<:Ansatz,N<:NamedTuple} ... end
```
This makes the `TensorNetwork` type a lil bit more cumbersome, but avoids mutability bugs and makes its use easier. It actually implements a kind of _attribute inheritance_ pattern that perfectly fits our use case.
With this PR, we can:
- Easily check if the appropriate metadata has been passed.
- Inherit metadata fields from ansatz super types (some kind of _attribute inheritance_ seen in C/C++/Java... almost any other OOP language).
- Avoid mutability issues of the `metadata` field: delete metadata, cast to incorrect type, ...
And because the `metadata` …
> Refactor `metadata` field in `TensorNetwork` to parametric `NamedTuple` type

- src/Quantum/Quantum.jl
- test/MatrixProductOperator_test.jl
- test/MatrixProductState_test.jl
This pull request addresses the issue encountered (resolves #64) when computing the `norm` of a Matrix Product Operator (MPO).
The problem arises when the function attempts to replace a tensor label in a tensor network with a new one that already exists. This scenario often occurs with MPOs and other tensor structures with multiple `interlayer` connections, as the `plug` `labels` might not be in the same order in the state and its adjoint.
This error was not encountered with Matrix Product States (MPS) because they have a single `interlayer` that matches their adjoint.
In this PR we have corrected this error and we also have introduced tests to validate the `norm` function for both MPS and MPO.
> Fix `hcat` function to handle label replacement in tensor networks correctly

- docs/make.jl
- docs/src/quantum/peps.md
- src/Quantum/PEP.jl
- src/Quantum/Quantum.jl
- src/Tenet.jl
- src/TensorNetwork.jl
This PR closes #8. It implements an initial version of the `ProjectedEntangledPair` ansatz.
There are some things to do yet, like normalized random initialization, contraction or tests. But I would like to merge this now so we have more ansatzs than MPS to test functionalities.
> Implement `ProjectedEntangledPair` ansatz

- src/TensorNetwork.jl
- test/Quantum_test.jl
- test/TensorNetwork_test.jl
This PR fixes issue #69 (resolves #69). The previous implementation did not raise a `DimensionMismatch` error in the `TensorNetwork` constructor function for inconsistent dimensions across tensors sharing the same index label. This issue could lead to incorrect results when working with `TensorNetwork` objects.
In response, we have implemented a dimensionality check in the `TensorNetwork` constructor function, ensuring consistency across tensors that share an index label. This is similar to the check that already exists in the `push!` method.
Furthermore, to confirm that both the `TensorNetwork` constructor and `push!` methods are functioning correctly, we have added tests to ensure they throw a `DimensionMismatch` error when encountering inconsistent dimensions.
With our fix, a …
> Fix `DimensionMismatch` not thrown in `TensorNetwork` constructor

- src/Quantum/MP.jl
- src/Quantum/PEP.jl
- src/Quantum/Quantum.jl
- src/Tenet.jl
- test/MatrixProductOperator_test.jl
- test/MatrixProductState_test.jl
In this PR, we resolve #77 by extending our `MatrixProduct` and `ProjectedEntangledPair` types to include support for infinite boundary conditions, materialized in the infinite Matrix Product States (iMPS) and infinite Projected Entangled Pair States (iPEPS). This creates a structure where the tensors cycle periodically, emulating an infinite system by using a finite system unit cell that repeats itself. 
The `tensors`, `Base.show` and `Base.length` functions have been extended to support `TensorNetworks` with `Infinte` boundary conditions. Additional unit tests have been added to ensure the proper functioning of these new boundary conditions for both the `MPS` and `MPO` structures.
Nevertheless, the visualization of infinite boundary types is not yet supported and we should think about …
> Implement `Infinite` `Boundary` Conditions for `MatrixProduct` and `ProjectedEntangledPair` Types

- docs/src/transformations.md
- src/Transformations.jl
This PR enhances the documentation of the `transform` functions. We fixed the previous text and, for the transformations that enabled it, we added a small visual example showing how that particular transformation work.
Moreover, we fixed a minor problem in the `DiagonalReduction` transformation, where the COPY tensor created did not have the `dual` metadata, which is necessary to display the transformed tensor network correctly.
> Enhance `Tranformations` docs

- src/Quantum/MP.jl
- src/Quantum/PEP.jl
- src/Quantum/Quantum.jl
- src/Tenet.jl
- test/MatrixProductOperator_test.jl
- test/MatrixProductState_test.jl
> Remove all references to `Infinite` trait

- src/Numerics.jl
- test/Numerics_test.jl
Currently, the `qr` decomposition on a `Tensor` t defaults to the "full" mode, which given a matrix `(M, N)` with `M>N` we get a `Q` matrix with size `(M, M)` and `R` with size `(N, N)`. This is counter-intuitive since these two tensors share a virtual index but they do not have the same dimensions. 
In this PR we fix this by adding a `mode` argument to the `qr` function (which by default is set to `:reduced`). With `mode=:reduced`, it will ensure that the dimensions of the virtual index match and with `mode=:full` the `qr` functions returns the full matrices.
This enhancement facilitates more intuitive operations as illustrated below:
```julia
julia> A = Tensor(rand(32, 8), (:i, :j))
32×8 Tensor{Float64, 2, Matrix{Float64}}: ...
julia> Q, R = qr(A, :reduced; …
```
> Enhance `qr` function with `mode` argument

- Project.toml
- docs/src/tensors.md
- src/Numerics.jl
- src/Tensor.jl
- src/Transformations.jl
- test/Numerics_test.jl
This PR adds the new `lu` function for tensors, extending the `LinearAlgebra.lu` function (resolve #26). The new `lu` function returns the LU decomposition of a `Tensor`, where the tensor can be recovered by contracting the permutation tensor `P`, the tensor `L`, and tensor `U`. The tensors `L` and `U` are reshaped versions of the original lower and upper triangular matrices obtained during the decomposition process, respectively.
This implementation is inspired by the LU decomposition in the `scipy` library, as it returns the permutation tensor `P` allowing the original tensor `A` to be recovered with the contraction `A = P * L * U`. This contrasts with `LinearAlgebra`, where the permutation vector `p` is returned, and the original matrix can be recovered with `P' * A = L * U` (where …
> Add `lu` decomposition for `Tensor`s

- Project.toml
- src/TensorNetwork.jl
- test/TensorNetwork_test.jl
This PR resolves issue #147 by introducing a new macro `@unsafe_region`, allowing users to temporarily relax index size checks when performing tensor operations within a specified code block. This feature is particularly useful for updating tensors in a tensor network where intermediate steps might involve tensors with mismatched sizes.
```julia
julia> tn = TensorNetwork([
Tensor(rand(2, 2, 2), [:i, :j, :k]),
Tensor(rand(2, 2), [:j, :l]),
Tensor(rand(2, 2, 2, 2), [:l, :k, :m, :n]),
Tensor(rand(2, 2, 2), [:n, :o, :p])])
TensorNetwork (#tensors=4, #inds=8)
julia> a = Tensor(rand(3, 2), (:i, :j)); push!(tn, a)
ERROR: DimensionMismatch: size(tensor,i)=3 but should be equal to size(tn,i)=2
Stacktrace:
[1] push!(tn::TensorNetwork, tensor::Tensor{Float64, 2, Matrix{Float64}}) …
```
> Implement `@unsafe_region` macro for relaxed tensor operations

- ext/TenetChainRulesCoreExt/non_diff.jl
- ext/TenetQuacExt.jl
- ext/TenetYaoExt.jl
- src/Ansatz/Chain.jl
- src/Ansatz/Dense.jl
- src/Ansatz/Grid.jl
- src/Ansatz/Product.jl
- src/Helpers.jl
- src/TensorNetwork.jl
There have been reports that when generating too many indices automatically (using the atomic counter) in the same Julia session, it breaks.
This usually happens due to repeatedly generating `TensorNetworks`.
This PR fixes it by introducing `IndexCounter`: a small wrapper over the currently global behaviour.
If merged, all `TensorNetwork`s would start from the same index.
> Replace the global index counter generator for a local data structure

- src/Ansatz/Chain.jl
In this PR, we replace the former Gram-Schmidt method for random chain initialization by a `QR` method, which applies the `qr` decomposition to some random tensors in order to get a randomly normalized right-canonized `MPS`.
Additionally, we benchmarked both methods and we conclude that the new method outscales the former in terms of running time, memory required and allocations produced.
· `Gram-Schmidt` method:
```julia
julia> using Tenet; using BenchmarkTools
julia> @btime mps = rand(Chain, Open, State; n=50, χ=300)
2.002 s (53812 allocations: 122.75 MiB)
MPS (inputs=0, outputs=50)
julia> @btime mpo = rand(Chain, Open, Operator; n=50, χ=200)
1.537 s (63338 allocations: 120.70 MiB)
MPO (inputs=50, outputs=50)
```
· `QR` method:
```julia
julia> using Tenet; using BenchmarkTools
julia> …
```
> Replace Gram-Schmidt method by QR for random Chain initialization

- src/Quantum.jl
- src/TensorNetwork.jl
- test/Quantum_test.jl
- test/TensorNetwork_test.jl
This PR resolves #177 by correctly fixing the reindex of the `site` indices. To do that, we modified the `replace!` function by returning the final index mapping. I believe this is the most efficient way to do this since we could also get the mapping by comparing the tensor before and after the `replace!`, but this seems to do unnecessary work.
Now the following code works fine:
```julia
julia> mps = rand(Chain, Open, State; n=5, p=2, χ=20)
MPS (inputs=0, outputs=5)
julia> mpo = rand(Chain, Open, Operator; n=5, χ=2, p=2)
MPO (inputs=5, outputs=5)
julia> inds(mpo, at = Site(1))
:A
julia> inds(mpo, at = Site(1; dual=true))
:F
julia> Tenet.@reindex! outputs(mps) => inputs(mpo)
MPO (inputs=5, outputs=5)
julia> inds(mpo, at = Site(1))
:A
julia> inds(mpo, at = Site(1; dual=true))
:O
julia> …
```
> Fix reindex! by returing the final index replace mapping

- src/Ansatz/Chain.jl
- test/Chain_test.jl
This PR fixes the `evolve!` function, which failed from the changes in #170. In addition, in this PR we add covering tests for the `evolve!` and `expect` functions.
> Fix `evolve!` function

- src/Quantum.jl
- test/Quantum_test.jl
With this PR, `inds(tn; set=:physical)` would return the physical indices annotated in the `sites` dict of `Quantum`, and `inds(tn; set=:virtual)` would return the virtual indices (i.e. the set difference between all the indices and the physical indices).
> Implement `inds` method for physical and virtual indices

- src/TensorNetwork.jl
if you call inds(::Chain) with the wrong  set = option, Tenet throws an obscure error - I don't know if this is due to a wrong use of MethodError, I changed it for an ArgumentError and it works. I also added some extra info, so now it throws
```
julia> inds(psi, set=:sergio)
ERROR: ArgumentError: unknown query: set=sergio.
Possible options are:
:all, :open :inner :hyper :parallelto
For Quantum also :physical :virtual
```
> fix error message for wrong set in inds()

- src/Quantum.jl
- src/TensorNetwork.jl
`conj` (and thus `adjoint` because it calls `conj`) was mutating the arrays of the original `TensorNetwork` when it shouldn't.
The reason is that we were doing a _shallow_ copy (i.e. `copy`) instead of a _deep_ copy (i.e. `deepcopy`).
> Fix mutation on `conj`, `adjoint`

- src/Quantum.jl
- src/Tenet.jl
- src/TensorNetwork.jl
- test/TensorNetwork_test.jl
> Introduce `groupinds!` function to group parallel inds

- src/TensorNetwork.jl
This PR resolves #191, so now if we use `replace!` and it throws an error, we do not get any destructive problems.
```julia
julia> psi = rand(Chain, Open, State; n=5, χ=8)
MPS (inputs=0, outputs=5)
julia> i2 = inds(tensors(psi, at=Site(2)))
3-element Vector{Symbol}: ...
julia> t2n_alt = Tensor(rand(2,2,10), i2)
2×2×10 Tensor{Float64, 3, Array{Float64, 3}}: ...
julia> size.(tensors(psi))
5-element Vector{Tuple{Int64, Int64, Vararg{Int64}}}:
(2, 2)
(2, 2, 4)
(4, 2, 4)
(4, 2, 2)
(2, 2)
julia> replace!(psi, tensors(psi,at=Site(2)) => t2n_alt)
ERROR: DimensionMismatch: size(tensor,G)=10 but should be equal to size(tn,G)=4
Stacktrace:
[1] push!(tn::TensorNetwork, tensor::Tensor{Float64, 3, Array{Float64, 3}})
@ Tenet ~/git/Tenet.jl/src/TensorNetwork.jl:538
[2] …
```
> Fix error throw in `replace!`

- ext/TenetYaoBlocksExt.jl
- test/integration/YaoBlocks_test.jl
This PR resolves #210 by transposing the matrices received from `Yao`. This has to be done, since `Yao`'s conventions seem to be (outputs, inputs), rather than (inputs, outputs)  that we usually do. See that this problem is now fixed:
```julia
julia> using Yao; using Tenet
julia> phase = 2*acos(1/sqrt(3))
1.9106332362490184
julia> circuit = chain(n_qubits, put(1=>Yao.Ry(phase)), Yao.control(1, 2=>Yao.H), Yao.control(2, 3=>Yao.X), Yao.control(1, 2=>Yao.X), put(1=>Yao.X))
nqubits: 3
chain
├─ put on (1)
│  └─ rot(Y, 1.9106332362490184)
├─ control(1)
│  └─ (2,) H
├─ control(2)
│  └─ (3,) X
├─ control(1)
│  └─ (2,) X
└─ put on (1)
└─ X
julia> SV_Yao = apply!(zero_state(n_qubits), circuit) # circuit|000> 
ArrayReg{2, ComplexF64, Array...}
active qubits: 3/3
nlevel: 2
julia> statevec(SV_Yao) …
```
> Fix `Yao` extension by properly transposing matrices

- src/TensorNetwork.jl
- test/TensorNetwork_test.jl
> Fix index dimension mismatch in `TensorNetwork` construction

- src/Ansatz/MPS.jl
- test/Ansatz_test.jl
- test/MPS_test.jl
> Implement an MPS method initializing the tensors to identity (copy-tensors)

- src/Ansatz/Chain.jl
- src/Helpers.jl
This PR modifies the previously hard-coded threshold inside the `truncate!` function, which was fixed to `1e-16`, to the proper epsilon value of the chain's `eltype`, making it more flexible and general.
> Replace hard-coded `truncate!` `threshold` with the epsilon value of the chain's `eltype`

- src/TensorNetwork.jl
- test/TensorNetwork_test.jl
This PR resolves #225 by fixing the problem with `replace!` when the same `Tensor` appears in both positions of the `pair` argument. Previously, since we did not have any specific check for this case, the `replace!` function had a `push!` that did not add the tensor since it was already present, but then, because we had a `delete!` after the `push!`, the `Tensor` got deleted.
We fixed this problem by adding a condition in the `replace!` function that checks if the two tensors are equal, and if they are, the function returns the `TensorNetwork` without changes.
Additionally (and importantly @bsc-quantic/software !), this PR also fixes the commented-out tests for the `replace!` function, and we have extended these tests to cover the specific case that this PR addresses.
> Fix `replace!` function when replacing a `Tensor` with itself in `pair` argument

- src/Quantum.jl
- src/TensorNetwork.jl
- test/Quantum_test.jl
- test/TensorNetwork_test.jl
This PR modifies the `adjoint` and `conj` functions for `AbstractQuantum` and `AbstractTensorNetwork` types to prevent errors when tensors contain immutable arrays. Instead of performing in-place operations, the functions now return a modified copy of the input.
Some tensors within a `TensorNetwork` may have immutable arrays in their parent structures. Performing in-place operations like `conj!` or `adjoint!` on these tensors can lead to errors because immutable arrays do not support the `setindex!` operation required for in-place modification. 
```julia
julia> using YaoBlocks
julia> c = YaoBlocks.chain(2)
julia> c = YaoBlocks.chain(2, c, put(1 => X))
julia> c = YaoBlocks.chain(2, c, put(2 => X))
julia> c = YaoBlocks.chain(2, c, put(1 => X))
julia> allzeros = …
```
> Avoid in-place operations in `adjoint` and `conj` functions

- src/Helpers.jl
- src/TensorNetwork.jl
- test/TensorNetwork_test.jl
This PR resolves #230 by refactoring the `@unsafe_region` macro. In this PR, we added a new field on the `TensorNetwork` struct `check_index_sizes::Ref{Bool}`. When `true`, there will be no inconsistent-dimension checks on the `push!` functions.
Now, `@unsafe_region` just modifies this value in the `field` of the specific `TensorNetwork` passed in the arguments, and keeps track of all the possible copies created inside the macro block.
Let's see how we fixed the example we show in #230:
```julia
julia> tn = TensorNetwork([
Tensor(ones(2, 2), [:a, :b]),
Tensor(ones(2, 2), [:b, :c])
])
TensorNetwork (#tensors=2, #inds=3)
julia> tn2 = copy(tn)
TensorNetwork (#tensors=2, #inds=3)
julia> Tenet.@unsafe_region tn begin # Now it errors properly!
tensor = Tensor(ones(3, 2), [:c, …
```
> Refactor `@unsafe_region` macro

- src/Transformations.jl
- test/Transformations_test.jl
This PR fixes the `transform!` function for the `Truncate` transformation to properly use the `atol` argument. Previous this PR, the function had `atol` defined but was not used in the function. 
Additionally, we enhanced the tests for this function so now it covers for the proper usage of `atol`.
> Fix `Truncate` transformation to correclty use `atol` argument

- src/Ansatz.jl
- src/MPS.jl
This PR adds `Form`-specific constructors for the `MPS` struct, which allows us to create Matrix Product States with an specific canonical `Form` directly on the constructor. I believe this is the proper way to go, and we added a `check_canonical_form` `kwarg` that, if `true` (default), it will check if the `MPS` fulfills the canonical form.
> Add `Form`-specific constructors for `MPS`

- ext/TenetQuacExt.jl
- test/integration/Quac_test.jl
This PR fixes a problem with the `Quantum` function for `Quac.Gate` argument. Before this PR, this function had legacy code from our previous `Dense` structure, which was replaced in PR #223. Specifically, we still had the `sites` kwarg, which is now replaced by the second argument of `Quantum`.
Additionally, in this PR we also add a `@testset` `"Gate"` in the `Quac` integration tests to cover for this issue.
> Fix `Quantum` function for `Quac.Gate` type

- src/Ansatz.jl
- src/MPS.jl
- test/MPS_test.jl
This PR resolves a bug found in the `truncate!` function that erroed when `maxdim` kwarg was larger than the `size` of the bond that was about to truncate. In a similar way, it also erroed when the `threshold` was lower than the smaller element in the `spectrum` that was used to truncate.
Moreover, we fixed the `mixed_canonize!` function, since previously did not work as the `truncate!` function expected for `MPS` with `MixedCanonical` forms. We also fixed an unnecessary canonization step in the `truncate!` for `Canonical` forms.
Without this PR:
```julia
julia> using Tenet; using Test; using LinearAlgebra
julia> gate = Quantum(reshape(LinearAlgebra.I(4), 2, 2, 2, 2), [site"2", site"3", site"2'", site"3'"])
Quantum (inputs=2, outputs=2)
julia> ψ = MPS([rand(2, 2), rand(2, 2, 2), rand(2, …
```
> Fix `truncate!` function

- src/Ansatz.jl
- src/MPS.jl
- src/Quantum.jl
- test/MPS_test.jl
This PR refactors the `simple_update!` function so now it properly uses the $\Lambda$ tensors of an `MPS` in the `Canonical` form to `evolve` the state without the need of recanonizing it.
Additionally, we also added the `kwarg` of `normalize` in the `canonize!` function.
> Enhance `simple_update!` for `MPS` in the `Canonical` form

- src/Ansatz.jl
- src/MPS.jl
- test/MPS_test.jl
This PR enhances the `evolve!` to handle the evolution of an `MPS` with an `MPO` in different canonical forms. Additionally, it includes new test cases to verify the correctness of the evolution functions.
@starsfordummies Please take a look and tell me what do you think!
Also we should take a look at issue #238 (which asks to extend `mixed_canonize!` so it dispatches on `Form`). So if we already have an `mps` that is in `MixedCanonical`, there is no need to do the full sweep if we just want to change the ortogonality center.
```julia
julia> using Tenet; using Test
julia> ψ = MPS([rand(2, 2), rand(2, 2, 2), rand(2, 2, 2), rand(2, 2, 2), rand(2, 2)]); normalize!(ψ)
MPS (inputs=0, outputs=5)
julia> mpo = rand(MPO; n=5, maxdim=4)
MPO (inputs=5, outputs=5)
julia> ϕ_1 = evolve!(canonize(ψ), …
```
> Add `evolve!` for evolution of an `MPS` with an `MPO`

- src/MPS.jl
This PR adds the default `maxdim` value for `rand` `MPS` and `MPO` constructor.
> Add default `maxdim` value in `rand` `MPS` and `MPO` constructor

- src/Ansatz.jl
- src/MPS.jl
This PR includes changes to `evolve`-related functions to add support for additional keyword arguments (`kwargs...`) in several functions. This enhancement allows for more flexible function calls by passing extra parameters as needed.
This is useful for example when we want to pass a `kwarg` into `truncate`.
> Add missing `kwargs...` in `evolve`-related functions

- ext/TenetChainRulesCoreExt/projectors.jl
- ext/TenetChainRulesCoreExt/rrules.jl
- ext/TenetChainRulesCoreExt/tangents.jl
- ext/TenetKrylovKitExt.jl
- ext/TenetReactantExt.jl
- src/Ansatz.jl
- src/Helpers.jl
- src/Numerics.jl
- src/Tensor.jl
- src/TensorNetwork.jl
- test/Ansatz_test.jl
- test/Numerics_test.jl
- test/TensorNetwork_test.jl
- test/Tensor_test.jl
- test/integration/Dagger_test.jl
- test/integration/KrylovKit_test.jl
Current implementation of `inds(::Tensor)` is to return the `Vector{Symbol}`, but this has the problem that mutating will modify the one from the original tensor too.
> Refactor `inds(::Tensor)` to return `Tuple`

- src/Numerics.jl
- test/Numerics_test.jl
This PR resolves a bug where the type `T` does NOT exist but it should be type `Tensor` in multiplication operation.
> Fix tensor-number multiplication

- docs/src/manual/ansatz/mps.md
This PR continues with the development started in PR #262, which is a bit behind the chain of commits so we are redoing the PR.
This PR updates the `MPS` manual, accounting with the changes from `MPS` refactor (PR #232) and thus adding explanation of the different canonical forms we support. I think it makes sense that the manual for the canonical forms is in this `MPS` manual.
> Update `MPS` manual in docs

- docs/src/manual/ansatz/product.md
This PR addresses issue #180 by updating the tutorial for the `Product` struct.
> Update `Product` manual

- ext/TenetYaoBlocksExt.jl
- test/integration/YaoBlocks_test.jl
When converting a `Yao` circuit to a `Tenet` tensor network, the gates' sites and its duals had an incorrect order causing a bad interconnection inside the tensor network. This is, the outputs were taken as inputs and viceversa giving the following inconsistent results:
```julia
julia> U.mat
4×4 Matrix{ComplexF64}:
0.512459+0.606575im   0.88142+0.973414im  0.617066+0.694744im    0.765335+0.470115im
0.196287+0.34693im   0.618943+0.114418im  0.905947+0.0761331im   0.237069+0.318266im
0.586231+0.158916im  0.189495+0.691832im  0.991734+0.241937im    0.675667+0.365597im
0.303253+0.705869im  0.575559+0.778916im  0.511385+0.380175im   0.0958053+0.303978im
julia> Tenet.contract(merge(zerost, Quantum(circuit), onest')) # Tenet <11|U|00>
0-dimensional Tensor{ComplexF64, 0, Array{ComplexF64, 0}}: …
```
> Fix sites in Yao to Tenet conversion

- src/MPS.jl
- test/MPO_test.jl
- test/MPS_test.jl
> Unit test of canonization in MPO

- src/Ansatz.jl
- src/MPS.jl
- src/Tenet.jl
- test/unit/MPO_test.jl
- test/unit/MPS_test.jl
Deprecation warnings remain. This PR just fixes calls to deprecated methods on internal code and tests.
@jofrevalles I've renamed `contract!` on `MPS` for contracting the $\Lambda$ to a tensor to `absorb!` because (1) it was conflicting with `contract!(; bond)` and the dispatch wasn't working, and (2) I think semantically this is more representative. wdyt?
> Update calls to deprecated methods

- src/TensorNetwork.jl
- test/unit/TensorNetwork_test.jl
This PR resolves #330 by adding a line in `replace!` function that checks if the old `Tensor` is in the `TensorNetwork`, and `throws` an `ArgumentError` if it is not.
Additionally, we also added a test to cover for this issue.
```julia
julia> mps = rand(MPS; n=6)
MPS (inputs=0, outputs=6)
julia> A = tensors(mps, at=Site(2))
2×2×4 Tensor{Float64, 3, Array{Float64, 3}}: ...
julia> B = Tensor(rand(size(A)...), inds(A)) # New Tensor, same inds as A but different data
2×2×4 Tensor{Float64, 3, Array{Float64, 3}}: ...
julia> C = Tensor(rand(size(A)...), inds(A)) # New Tensor, same inds as A but different data
2×2×4 Tensor{Float64, 3, Array{Float64, 3}}: ...
julia> replace!(mps, B => C) # Now we get an error :)
ERROR: ArgumentError: Old tensor not found in TensorNetwork …
```
> Add check in `replace!` to ensure old `Tensor` is in the `TensorNetwork`

- src/Ansatz.jl
In this PR we extend the `expect` function to account on `Canonical` form, so now we only contract local tensors instead of the full `MPS`. We left the old implementation for `NonCanonical` and `MixedCanonical` forms, and we put a "TODO" comment on the latter to extend it in the future.
You can see how we now get a much better performance from both `runtime` and `memory`:
```julia
julia> using BenchmarkTools
julia> Z = [1 0; 0 -1]
2×2 Matrix{Int64}:
1   0
0  -1
julia> observable = Gate(Tensor(Z, (:i, :iᶜ)), [Site(5), Site(5, dual=true)])
Gate([1 0; 0 -1], Site[5, 5'])
julia> mps = rand(MPS; n=12); canonize!(mps)
MPS (inputs=0, outputs=12)
julia> @benchmark expect(mps, Quantum(observable)) # NEW implementation
BenchmarkTools.Trial: 4242 samples with 1 evaluation per …
```
> Extend `expect` function to account on `form`
